// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWuJ82rO2eAKqfB6Mz3lwqPm75NwahnA',
    appId: '1:118163497961:web:dda78d1aebc5396e916178',
    messagingSenderId: '118163497961',
    projectId: 'timifix-e8cc8',
    authDomain: 'timifix-e8cc8.firebaseapp.com',
    storageBucket: 'timifix-e8cc8.appspot.com',
    measurementId: 'G-YHJ2XV1R9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTCkAukFg8YjTkJ79wpoiR-73KRol-gQ',
    appId: '1:118163497961:android:1660c1d0c6956259916178',
    messagingSenderId: '118163497961',
    projectId: 'timifix-e8cc8',
    storageBucket: 'timifix-e8cc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqFRiv207YhVHRSqsXKRrZXVKq6AWOy8',
    appId: '1:118163497961:ios:fa9c3875ed03fcda916178',
    messagingSenderId: '118163497961',
    projectId: 'timifix-e8cc8',
    storageBucket: 'timifix-e8cc8.appspot.com',
    iosBundleId: 'com.example.timiFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbqFRiv207YhVHRSqsXKRrZXVKq6AWOy8',
    appId: '1:118163497961:ios:fa9c3875ed03fcda916178',
    messagingSenderId: '118163497961',
    projectId: 'timifix-e8cc8',
    storageBucket: 'timifix-e8cc8.appspot.com',
    iosBundleId: 'com.example.timiFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWuJ82rO2eAKqfB6Mz3lwqPm75NwahnA',
    appId: '1:118163497961:web:b75119706a99344f916178',
    messagingSenderId: '118163497961',
    projectId: 'timifix-e8cc8',
    authDomain: 'timifix-e8cc8.firebaseapp.com',
    storageBucket: 'timifix-e8cc8.appspot.com',
    measurementId: 'G-YJ31ZRTXMT',
  );

}